import platform

Import('env')

if platform.system() == 'Windows':
    ragel = r'nadamq\tools\ragel-6.9\ragel.exe'
else:
    ragel = 'ragel'

socket_fsm_src = Command('packet_socket_fsm_actions.cpp',
                         'packet_socket_fsm_actions.rl',
                         '%s -G2 -o $TARGET $SOURCE' % ragel)

Depends(socket_fsm_src, 'packet_socket_fsm.rl')

packet_actions_src = Command('packet_actions.cpp', 'packet_actions.rl',
                             '%s -G2 -o $TARGET $SOURCE' % ragel)

Depends(packet_actions_src, 'packet.rl')
#Depends(packet_dot, 'packet.rl')
#Depends(packet_pdf, 'packet.rl')

crc_objs = env.Object(['crc_common.cpp'])
packet_actions = env.Object([packet_actions_src])
