packet_actions_src = Command('packet_actions.cpp', 'packet_actions.rl',
                             'ragel -G1 -o $TARGET $SOURCE')
packet_dot = Command('packet_actions.dot', 'packet_actions.rl',
                     'ragel -V -o $TARGET $SOURCE')
packet_pdf = Command('packet_actions.pdf', packet_dot,
                     'dot -Tpdf -o $TARGET $SOURCE')

Depends(packet_actions_src, 'packet.rl')
Depends(packet_dot, 'packet.rl')
Depends(packet_pdf, 'packet.rl')

packet_actions = Object([packet_actions_src, 'crc-16.c'],
                        CPPDEFINES=['VERBOSE_STATES'])
Program(['test_packet_parser.cpp', packet_actions],
        CCFLAGS=['-g', '-O0'])
