/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.2.8-dev at Wed Apr 30 08:19:49 2014. */

#include "simple.pb.h"



const pb_field_t EchoRequest_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t RAMSizeRequest_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t RAMDataSizeRequest_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t RAMBSSSizeRequest_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t RAMHeapSizeRequest_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t RAMStackSizeRequest_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t RAMFreeRequest_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t CommandRequest_fields[9] = {
    PB_FIELD2(  1, ENUM    , REQUIRED, STATIC  , FIRST, CommandRequest, type, type, 0),
    PB_FIELD2(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, CommandRequest, echo, type, &EchoRequest_fields),
    PB_FIELD2(  3, MESSAGE , OPTIONAL, STATIC  , OTHER, CommandRequest, ram_size, echo, &RAMSizeRequest_fields),
    PB_FIELD2(  4, MESSAGE , OPTIONAL, STATIC  , OTHER, CommandRequest, ram_data_size, ram_size, &RAMDataSizeRequest_fields),
    PB_FIELD2(  5, MESSAGE , OPTIONAL, STATIC  , OTHER, CommandRequest, ram_bss_size, ram_data_size, &RAMBSSSizeRequest_fields),
    PB_FIELD2(  6, MESSAGE , OPTIONAL, STATIC  , OTHER, CommandRequest, ram_heap_size, ram_bss_size, &RAMHeapSizeRequest_fields),
    PB_FIELD2(  7, MESSAGE , OPTIONAL, STATIC  , OTHER, CommandRequest, ram_stack_size, ram_heap_size, &RAMStackSizeRequest_fields),
    PB_FIELD2(  8, MESSAGE , OPTIONAL, STATIC  , OTHER, CommandRequest, ram_free, ram_stack_size, &RAMFreeRequest_fields),
    PB_LAST_FIELD
};

const pb_field_t EchoResponse_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t RAMSizeResponse_fields[2] = {
    PB_FIELD2(  1, UINT32  , REQUIRED, STATIC  , FIRST, RAMSizeResponse, result, result, 0),
    PB_LAST_FIELD
};

const pb_field_t RAMDataSizeResponse_fields[2] = {
    PB_FIELD2(  1, UINT32  , REQUIRED, STATIC  , FIRST, RAMDataSizeResponse, result, result, 0),
    PB_LAST_FIELD
};

const pb_field_t RAMBSSSizeResponse_fields[2] = {
    PB_FIELD2(  1, UINT32  , REQUIRED, STATIC  , FIRST, RAMBSSSizeResponse, result, result, 0),
    PB_LAST_FIELD
};

const pb_field_t RAMHeapSizeResponse_fields[2] = {
    PB_FIELD2(  1, UINT32  , REQUIRED, STATIC  , FIRST, RAMHeapSizeResponse, result, result, 0),
    PB_LAST_FIELD
};

const pb_field_t RAMStackSizeResponse_fields[2] = {
    PB_FIELD2(  1, UINT32  , REQUIRED, STATIC  , FIRST, RAMStackSizeResponse, result, result, 0),
    PB_LAST_FIELD
};

const pb_field_t RAMFreeResponse_fields[2] = {
    PB_FIELD2(  1, UINT32  , REQUIRED, STATIC  , FIRST, RAMFreeResponse, result, result, 0),
    PB_LAST_FIELD
};

const pb_field_t CommandResponse_fields[9] = {
    PB_FIELD2(  1, ENUM    , REQUIRED, STATIC  , FIRST, CommandResponse, type, type, 0),
    PB_FIELD2(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, CommandResponse, echo, type, &EchoResponse_fields),
    PB_FIELD2(  3, MESSAGE , OPTIONAL, STATIC  , OTHER, CommandResponse, ram_size, echo, &RAMSizeResponse_fields),
    PB_FIELD2(  4, MESSAGE , OPTIONAL, STATIC  , OTHER, CommandResponse, ram_data_size, ram_size, &RAMDataSizeResponse_fields),
    PB_FIELD2(  5, MESSAGE , OPTIONAL, STATIC  , OTHER, CommandResponse, ram_bss_size, ram_data_size, &RAMBSSSizeResponse_fields),
    PB_FIELD2(  6, MESSAGE , OPTIONAL, STATIC  , OTHER, CommandResponse, ram_heap_size, ram_bss_size, &RAMHeapSizeResponse_fields),
    PB_FIELD2(  7, MESSAGE , OPTIONAL, STATIC  , OTHER, CommandResponse, ram_stack_size, ram_heap_size, &RAMStackSizeResponse_fields),
    PB_FIELD2(  8, MESSAGE , OPTIONAL, STATIC  , OTHER, CommandResponse, ram_free, ram_stack_size, &RAMFreeResponse_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
STATIC_ASSERT((pb_membersize(CommandRequest, echo) < 65536 && pb_membersize(CommandRequest, ram_size) < 65536 && pb_membersize(CommandRequest, ram_data_size) < 65536 && pb_membersize(CommandRequest, ram_bss_size) < 65536 && pb_membersize(CommandRequest, ram_heap_size) < 65536 && pb_membersize(CommandRequest, ram_stack_size) < 65536 && pb_membersize(CommandRequest, ram_free) < 65536 && pb_membersize(CommandResponse, echo) < 65536 && pb_membersize(CommandResponse, ram_size) < 65536 && pb_membersize(CommandResponse, ram_data_size) < 65536 && pb_membersize(CommandResponse, ram_bss_size) < 65536 && pb_membersize(CommandResponse, ram_heap_size) < 65536 && pb_membersize(CommandResponse, ram_stack_size) < 65536 && pb_membersize(CommandResponse, ram_free) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_EchoRequest_RAMSizeRequest_RAMDataSizeRequest_RAMBSSSizeRequest_RAMHeapSizeRequest_RAMStackSizeRequest_RAMFreeRequest_CommandRequest_EchoResponse_RAMSizeResponse_RAMDataSizeResponse_RAMBSSSizeResponse_RAMHeapSizeResponse_RAMStackSizeResponse_RAMFreeResponse_CommandResponse)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
STATIC_ASSERT((pb_membersize(CommandRequest, echo) < 256 && pb_membersize(CommandRequest, ram_size) < 256 && pb_membersize(CommandRequest, ram_data_size) < 256 && pb_membersize(CommandRequest, ram_bss_size) < 256 && pb_membersize(CommandRequest, ram_heap_size) < 256 && pb_membersize(CommandRequest, ram_stack_size) < 256 && pb_membersize(CommandRequest, ram_free) < 256 && pb_membersize(CommandResponse, echo) < 256 && pb_membersize(CommandResponse, ram_size) < 256 && pb_membersize(CommandResponse, ram_data_size) < 256 && pb_membersize(CommandResponse, ram_bss_size) < 256 && pb_membersize(CommandResponse, ram_heap_size) < 256 && pb_membersize(CommandResponse, ram_stack_size) < 256 && pb_membersize(CommandResponse, ram_free) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_EchoRequest_RAMSizeRequest_RAMDataSizeRequest_RAMBSSSizeRequest_RAMHeapSizeRequest_RAMStackSizeRequest_RAMFreeRequest_CommandRequest_EchoResponse_RAMSizeResponse_RAMDataSizeResponse_RAMBSSSizeResponse_RAMHeapSizeResponse_RAMStackSizeResponse_RAMFreeResponse_CommandResponse)
#endif


